### ISSUE TITLE
Hope to be a contributor

### ISSUE THREAD

**Issue by soulstar9792** [decentral-ninja/website#6]
Hi, Decentral Ninja Team.

I hope this message finds you well.

I recently came across your project and feel impressed.
As a senior full-stack blockchain & AI developer with 8 years of experience, I am very interested in the opportunity to contribute to your project.
If you're open to collaboration or would like to discuss how I can add value to your project, I would love to connect.

Looking forward to hearing from you!

Best regards,
Joe

https://soulstar-0x.surge.sh/
[secondstar9792@gmail.com](mailto:secondstar9792@gmail.com)
https://t.me/secondstar9792

**Comment by Weedshaker** [comment]
Hey Joe,

thx for the message!
Would you be open to hold a jitsi call by occasion?

Let's continue our conversation here: https://decentral.ninja/?page=%2Fchat&websocket-url=wss%3A%2F%2Fthe-decentral-web.herokuapp.com%3Fkeep-alive%3D86400000&room=chat-https%3A%2F%2Fgithub.com%2Fdecentral-ninja%2Fwebsite%2Fissues%2F6

Cheers!
Weedo
